export interface RatioBaseCurrencyType {
  code: string
  key: number
  name: string
  ratio: number
}

export interface searchResultPayloadType {
  amount: number
  firstCurrency: string
  secondCurrency: string
}

export interface currenciesType {
  ada: string
  aed: string
  afn: string
  all: string
  amd: string
  ang: string
  aoa: string
  ars: string
  aud: string
  awg: string
  azn: string
  bam: string
  bbd: string
  bch: string
  bdt: string
  bgn: string
  bhd: string
  bif: string
  bmd: string
  bnb: string
  bnd: string
  bob: string
  brl: string
  bsd: string
  btc: string
  btn: string
  bwp: string
  byn: string
  byr: string
  bzd: string
  cad: string
  cdf: string
  chf: string
  clf: string
  clp: string
  cny: string
  cop: string
  crc: string
  cuc: string
  cup: string
  cve: string
  czk: string
  djf: string
  dkk: string
  doge: string
  dop: string
  dzd: string
  egp: string
  ern: string
  etb: string
  etc: string
  eth: string
  eur: string
  fjd: string
  fkp: string
  gbp: string
  gel: string
  ggp: string
  ghs: string
  gip: string
  gmd: string
  gnf: string
  gtq: string
  gyd: string
  hkd: string
  hnl: string
  hrk: string
  htg: string
  huf: string
  idr: string
  ils: string
  imp: string
  inr: string
  iqd: string
  irr: string
  isk: string
  jep: string
  jmd: string
  jod: string
  jpy: string
  kes: string
  kgs: string
  khr: string
  kmf: string
  kpw: string
  krw: string
  kwd: string
  kyd: string
  kzt: string
  lak: string
  lbp: string
  link: string
  lkr: string
  lrd: string
  lsl: string
  ltc: string
  ltl: string
  lvl: string
  lyd: string
  mad: string
  mdl: string
  mga: string
  mkd: string
  mmk: string
  mnt: string
  mop: string
  mro: string
  mur: string
  mvr: string
  mwk: string
  mxn: string
  myr: string
  mzn: string
  nad: string
  ngn: string
  nio: string
  nok: string
  npr: string
  nzd: string
  omr: string
  pab: string
  pen: string
  pgk: string
  php: string
  pkr: string
  pln: string
  pyg: string
  qar: string
  ron: string
  rsd: string
  rub: string
  rwf: string
  sar: string
  sbd: string
  scr: string
  sdg: string
  sek: string
  sgd: string
  shp: string
  sll: string
  sos: string
  srd: string
  std: string
  svc: string
  syp: string
  szl: string
  thb: string
  theta: string
  tjs: string
  tmt: string
  tnd: string
  top: string
  trx: string
  try: string
  ttd: string
  twd: string
  tzs: string
  uah: string
  ugx: string
  usd: string
  usdt: string
  uyu: string
  uzs: string
  vef: string
  vnd: string
  vuv: string
  wst: string
  xaf: string
  xag: string
  xau: string
  xcd: string
  xdr: string
  xlm: string
  xmr: string
  xof: string
  xpf: string
  xrp: string
  yer: string
  zar: string
  zmk: string
  zmw: string
  zwl: string
}